# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake Build and Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-[0-9]+"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux:
    # The host should always be linux
    runs-on: ${{matrix.runner}}
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 4 arch/distro combinations
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
        distro: ["20.04"]
        include:
          - arch: amd64
            base: ubuntu
            runner: ubuntu-22.04
          - arch: arm64
            base: arm64v8/ubuntu
            runner: ubuntu-22.04-arm
          - arch: armhf
            base: arm32v7/ubuntu
            runner: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: addnab/docker-run-action@v3
        id: build
        with:
          image: ${{matrix.base}}:${{matrix.distro}}
          options: >
            -v ${{ github.workspace }}:/workspace
            -e SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
            -e DEBIAN_FRONTEND=noninteractive
          run: |
            set -e
            apt-get update -q -y
            apt-get install -q -y ca-certificates gpg wget lsb-release
            wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc --no-check-certificate | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
            echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/kitware.list >/dev/null
            apt-get update -q -y
            apt-get install -q -y build-essential cmake file git python3-pip ninja-build zip pkg-config curl
            pip3 install meson
            cd /workspace
            curl -LO https://github.com/na-trium-144/webcface/releases/download/v2.7.0/libwebcface-linux-${{matrix.arch}}.zip
            unzip libwebcface-*.zip -d /opt/webcface
            rm libwebcface-*.zip
            meson setup build --buildtype=release --prefix=/opt/webcface -Dversion_suffix= -Dcmake_prefix_path=/opt/webcface
            meson compile -C build || meson compile -C build
            DESTDIR=/workspace/dist meson install -C build --skip-subprojects

      - name: Create zip archive
        run: |
          cd ${{github.workspace}}/dist/opt/webcface/
          zip --symlinks -r ${{github.workspace}}/webcface-tools-linux-${{matrix.arch}}.zip *
      - uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: ${{github.workspace}}/*.zip
      - name: Prepare deb package files
        run: |
          mkdir .debpkg
          cp -r dist/opt .debpkg/
          prefix=.debpkg/opt/webcface
          absprefix=/opt/webcface

          mkdir -p .debpkg/usr/bin
          for file in $prefix/bin/*; do
            echo $absprefix/bin/$(basename $file)
            ln -s $absprefix/bin/$(basename $file) .debpkg/usr/bin/
          done

          mkdir -p .debpkg/usr/share/doc
          echo $absprefix/share/doc/webcface-tools
          ln -s $absprefix/share/doc/webcface-tools .debpkg/usr/share/doc/

          mkdir -p .debpkg/usr/lib/systemd/system
          echo $absprefix/lib/systemd/system/webcface-launcher.service
          ln -s $absprefix/lib/systemd/system/webcface-launcher.service .debpkg/usr/lib/systemd/system/

      - name: Create dist deb package
        uses: jiro4989/build-deb-action@v3
        with:
          package: webcface-tools
          package_root: .debpkg
          maintainer: "na-trium-144 <na-trium-144@users.noreply.github.com>"
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: ${{matrix.arch}}
          desc: 'WebCFace Client Applications'
      - uses: actions/upload-artifact@v4
        with:
          name: linux-deb-${{ matrix.arch }}
          path: ${{github.workspace}}/*.deb

  build-macos:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    runs-on: macos-13
    name: Build on macos-13 ${{matrix.arch}}
    steps:
    - name: Install webcface
      run: |
        curl -LO https://github.com/na-trium-144/webcface/releases/download/v2.7.0/libwebcface-macos-universal.zip
        sudo unzip libwebcface-macos-universal.zip -d /opt/webcface
        rm libwebcface-macos-universal.zip

    - uses: actions/checkout@v4
    - uses: ilammy/setup-nasm@v1
    - name: Install Meson
      run: pip install meson
    - name: Install CMake and Ninja
      run: brew install cmake ninja

    - name: Setup Meson
      env:
        PKG_CONFIG_PATH: "/opt/webcface/lib/pkgconfig"
      run: >
        meson setup build
        --buildtype=release
        --prefix=/opt/webcface
        -Dversion_suffix=
        $([[ ${{matrix.arch}} = arm64 ]] && echo --cross-file scripts/cross/macos_arm64)
    - name: Compile
      run: meson compile -C build || meson compile -C build
    - name: install
      run: DESTDIR=${{github.workspace}}/dist meson install -C build --skip-subprojects
    - name: Create zip archive
      run: |
        cd ${{github.workspace}}/dist/opt/webcface/
        zip --symlinks -r ${{github.workspace}}/webcface-tools-macos-${{matrix.arch}}.zip *
    - uses: actions/upload-artifact@v4
      with:
        name: macos-${{matrix.arch}}
        path: ${{github.workspace}}/*.zip

  lipo-macos:
    runs-on: macos-13
    name: Create universal binary
    needs: [build-macos]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: macos-x86_64
          path: ${{github.workspace}}/
      - uses: actions/download-artifact@v4
        with:
          name: macos-arm64
          path: ${{github.workspace}}/
      - name: lipo
        run: |
          unzip webcface-tools-macos-x86_64.zip -d x86_64
          unzip webcface-tools-macos-arm64.zip -d arm64
          cp -R x86_64 universal
          for file in x86_64/bin/*; do
            rm universal/bin/$(basename $file)
            echo lipo x86_64/bin/$(basename $file) arm64/bin/$(basename $file) -create -output universal/bin/$(basename $file)
                 lipo x86_64/bin/$(basename $file) arm64/bin/$(basename $file) -create -output universal/bin/$(basename $file)
          done
      - name: Create zip archive
        run: |
          cd ${{github.workspace}}/universal
          zip --symlinks -r ${{github.workspace}}/webcface-tools-macos-universal.zip *
      - uses: actions/upload-artifact@v4
        with:
          name: macos-universal
          path: ${{github.workspace}}/webcface-tools-macos-universal.zip

  build-msvc:
    strategy:
      matrix:
        arch: ["x86", "x64"]
        buildtype: ["release"]
        include:
        - arch: x86
          devcmd: amd64_x86
        - arch: x64
          devcmd: amd64
        # - arch: arm64
        #   devcmd: amd64_arm64
    runs-on: windows-2019
    name: Build on Windows-2019 ${{matrix.arch}} ${{matrix.buildtype}}
    steps:
    - uses: actions/checkout@v4
    - name: download latest webcface
      run: |
        Invoke-WebRequest https://github.com/na-trium-144/webcface/releases/download/v2.7.0/libwebcface-windows-${{matrix.arch}}.zip -OutFile webcface.zip
        Expand-Archive -Path webcface.zip -DestinationPath webcface
        Remove-Item webcface.zip
    - name: Add webcface to path
      run: echo "${{github.workspace}}\webcface\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Install Meson
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install -y meson
    - name: Add meson to path
      run: echo "c:\Program Files\Meson" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{matrix.devcmd}}
    - name: Setup Meson release
      if: matrix.buildtype == 'release'
      run: >
        meson setup build
        --buildtype=${{matrix.buildtype}}
        "--prefix=C:\Program Files\webcface"
        -Dversion_suffix=
        --cross-file scripts/cross/msvc_${{matrix.arch}}
    - name: Compile
      run: |
        meson compile -C build
    - name: install
      env:
        DESTDIR: ${{github.workspace}}\dist
      run: meson install -C build --skip-subprojects

    - name: Create zip archive
      working-directory: '${{github.workspace}}\dist\Program Files\webcface'
      run: Compress-Archive * ${{github.workspace}}\webcface-tools-windows-${{matrix.arch}}.zip
    - uses: actions/upload-artifact@v4
      with:
        name: msvc-${{matrix.arch}}-${{matrix.buildtype}}
        path: ${{github.workspace}}/*.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, lipo-macos, build-msvc]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: linux-amd64
          path: ${{github.workspace}}/artifact
      - uses: actions/download-artifact@v4
        with:
          name: linux-deb-amd64
          path: ${{github.workspace}}/artifact
      - uses: actions/download-artifact@v4
        with:
          name: linux-arm64
          path: ${{github.workspace}}/artifact
      - uses: actions/download-artifact@v4
        with:
          name: linux-deb-arm64
          path: ${{github.workspace}}/artifact
      - uses: actions/download-artifact@v4
        with:
          name: linux-armhf
          path: ${{github.workspace}}/artifact
      - uses: actions/download-artifact@v4
        with:
          name: linux-deb-armhf
          path: ${{github.workspace}}/artifact
      - uses: actions/download-artifact@v4
        with:
          name: macos-universal
          path: ${{github.workspace}}/artifact
      - uses: actions/download-artifact@v4
        with:
          name: msvc-x86-release
          path: ${{github.workspace}}/artifact
      - uses: actions/download-artifact@v4
        with:
          name: msvc-x64-release
          path: ${{github.workspace}}/artifact
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: msvc-arm64
      #     path: ${{github.workspace}}/artifact

      - name: Release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_EMPTY_CHANGELOG: true
        with:
          args: artifact/*
