name: Meson Test (MacOS Clang)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

jobs:
  test-macos-clang:
    runs-on: macos-latest
    steps:
    - name: Install webcface
      run: |
        curl -LO https://github.com/na-trium-144/webcface/releases/download/v2.0.0/libwebcface-macos-universal.zip
        sudo unzip libwebcface-macos-universal.zip -d /opt/webcface
        rm libwebcface-macos-universal.zip

    - uses: actions/checkout@v4
    - name: Install meson
      run: |
        brew update --preinstall
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install meson

    - name: Setup Meson
      env:
        PKG_CONFIG_PATH: "/opt/webcface/lib/pkgconfig"
      run: >
        meson setup build
        --buildtype=debug
    - name: Compile
      run: meson compile -C build || meson compile -C build
