# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Meson Test (Windows MSVC)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-windows-msvc:
    runs-on: windows-2019
    steps:

    - uses: actions/checkout@v4
    - name: download latest webcface
      run: |
        Invoke-WebRequest https://github.com/na-trium-144/webcface/releases/download/v2.5.0/libwebcface-windows-x64.zip -OutFile webcface.zip
        Expand-Archive -Path webcface.zip -DestinationPath webcface
        Remove-Item webcface.zip
    - name: Add webcface to path
      run: echo "${{github.workspace}}\webcface\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install Meson
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install -y meson
    - name: Add meson to path
      run: echo "c:\Program Files\Meson" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Setup Meson
      run: >
        meson setup build
        --buildtype=debug
    - name: Compile
      run: |
        meson compile -C build

