# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Meson Test (Linux GCC)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

jobs:
  test-linux-gcc:
    runs-on: ubuntu-22.04
    steps:

    - name: Install ninja
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
    - name: Install meson
      run: pip install meson || pip install --break-system-packages meson

    - name: install latest webcface
      run: |
        curl -LO https://github.com/na-trium-144/webcface/releases/download/v2.4.0/webcface_2.4.0_amd64.deb
        sudo apt-get install -y ./*.deb
        rm ./*.deb

    - uses: actions/checkout@v4

    - name: Setup Meson
      run: >
        meson setup build
        --buildtype=debug
    - name: Compile
      run: meson compile -C build || meson compile -C build
    