name: CMake Test (MacOS Clang)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-macos-clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Homebrew
      run: brew update --preinstall
    - name: Install webcface from Homebrew
      run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install na-trium-144/webcface/webcface || true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

